"use client";

import {
  Bell,
  Check,
  CheckCircle2,
  ChevronRight,
  Clock3,
  Copy,
  Globe2,
  KeyRound,
  Mail,
  MapPin,
  Plus,
  Save,
  Settings as SettingsIcon,
  ShieldCheck,
  Smartphone,
  ToggleLeft,
  ToggleRight,
  UserRound,
  Users,
  Wifi,
  X,
} from "lucide-react";
import { useState } from "react";


type TabId = "general" | "pricing" | "notifications" | "security" | "team" | "integrations";
const tabs: { id: TabId; label: string; description: string }[] = [
  { id: "general", label: "Général", description: "Identité et configuration de base" },
  { id: "pricing", label: "Abonnements & Tarification", description: "Prix, essais et paiements" },
  { id: "notifications", label: "Notifications", description: "Alertes de l'équipe" },
  { id: "security", label: "Sécurité", description: "Accès et sessions" },
  { id: "team", label: "Équipe EduGoma", description: "Administrateurs internes" },
  { id: "integrations", label: "Intégrations", description: "Services connectés" },
];

function SettingCard({ title, description, children }: { title: string; description?: string; children: React.ReactNode }) { return <section className="rounded-md border border-[#e4eaf0] bg-white shadow-[0_2px_7px_rgba(33,60,84,0.025)]"><div className="border-b border-[#edf1f4] px-4 py-3"><h2 className="text-[12px] font-bold text-[#23394e]">{title}</h2>{description && <p className="mt-1 text-[9px] text-[#8a97a4]">{description}</p>}</div><div className="p-4">{children}</div></section>; }
function Field({ label, value, onChange, placeholder, type = "text" }: { label: string; value: string; onChange: (value: string) => void; placeholder?: string; type?: string }) { return <label className="block"><span className="text-[9px] font-bold uppercase tracking-[0.05em] text-[#8997a2]">{label}</span><input type={type} value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} className="mt-1.5 h-9 w-full rounded-md border border-[#dfe7ec] bg-white px-3 text-[10px] text-[#435c6e] outline-none focus:border-[#76a8cd]" /></label>; }
function Toggle({ enabled, onChange }: { enabled: boolean; onChange: () => void }) { return <button onClick={onChange} className={`relative h-5 w-9 shrink-0 rounded-full transition ${enabled ? "bg-[#3b9d7a]" : "bg-[#cdd9df]"}`} aria-pressed={enabled}><span className={`absolute top-0.5 h-4 w-4 rounded-full bg-white shadow-sm transition ${enabled ? "left-[18px]" : "left-0.5"}`} /></button>; }
function ToggleRow({ title, description, enabled, onChange }: { title: string; description: string; enabled: boolean; onChange: () => void }) { return <div className="flex items-center justify-between gap-4 border-b border-[#edf1f4] py-3 last:border-0"><div><p className="text-[10px] font-semibold text-[#526a7a]">{title}</p><p className="mt-1 text-[9px] leading-[1.4] text-[#8b99a3]">{description}</p></div><Toggle enabled={enabled} onChange={onChange} /></div>; }
function CheckOption({ label, checked, onChange }: { label: string; checked: boolean; onChange: () => void }) { return <button onClick={onChange} className="flex items-center gap-2 rounded px-2 py-1.5 text-left text-[10px] font-semibold text-[#637987] hover:bg-[#f5f8fa]"><span className={`flex h-4 w-4 items-center justify-center rounded border ${checked ? "border-[#3b9d7a] bg-[#3b9d7a] text-white" : "border-[#ccd9df] bg-white text-transparent"}`}><Check size={10} /></span>{label}</button>; }

function GeneralTab({ markDirty }: { markDirty: () => void }) { const [platformName, setPlatformName] = useState("EduGoma"); const [domain, setDomain] = useState("edugoma.cd"); const [provinces, setProvinces] = useState(["Nord-Kivu", "Sud-Kivu", "Kinshasa"]); return <div className="space-y-4"><SettingCard title="Identité de la plateforme" description="Les informations affichées aux écoles et aux utilisateurs"><div className="grid gap-4 sm:grid-cols-2"><Field label="Nom de la plateforme" value={platformName} onChange={(value) => { setPlatformName(value); markDirty(); }} /><Field label="Domaine principal" value={domain} onChange={(value) => { setDomain(value); markDirty(); }} /></div><div className="mt-4 flex items-center gap-3 rounded-md border border-dashed border-[#d8e3e8] p-3"><div className="flex h-10 w-10 items-center justify-center rounded-lg bg-[#102d48] text-white"><span className="text-[13px] font-extrabold">EG</span></div><div className="flex-1"><p className="text-[10px] font-bold text-[#516a7a]">Logo EduGoma</p><p className="mt-1 text-[8px] text-[#94a0a9]">PNG ou SVG · recommandé 256 × 256 px</p></div><button onClick={markDirty} className="rounded border border-[#dfe7ec] px-2.5 py-1.5 text-[9px] font-bold text-[#607887] hover:bg-[#f5f8fa]">Remplacer</button></div></SettingCard><SettingCard title="Préférences régionales" description="Valeurs par défaut pour les nouveaux espaces"><div className="grid gap-4 sm:grid-cols-2"><label className="block"><span className="text-[9px] font-bold uppercase tracking-[0.05em] text-[#8997a2]">Langue par défaut</span><select onChange={markDirty} className="mt-1.5 h-9 w-full rounded-md border border-[#dfe7ec] bg-white px-3 text-[10px] font-semibold text-[#536b7d]"><option>Français</option><option>English</option></select></label><label className="block"><span className="text-[9px] font-bold uppercase tracking-[0.05em] text-[#8997a2]">Fuseau horaire</span><select onChange={markDirty} className="mt-1.5 h-9 w-full rounded-md border border-[#dfe7ec] bg-white px-3 text-[10px] font-semibold text-[#536b7d]"><option>CAT — Africa/Lubumbashi</option><option>UTC</option></select></label></div><div className="mt-4"><p className="text-[9px] font-bold uppercase tracking-[0.05em] text-[#8997a2]">Provinces couvertes</p><div className="mt-2 flex flex-wrap gap-1.5">{["Nord-Kivu", "Sud-Kivu", "Kinshasa", "Ituri", "Haut-Katanga"].map((province) => <CheckOption key={province} label={province} checked={provinces.includes(province)} onChange={() => { setProvinces((current) => current.includes(province) ? current.filter((item) => item !== province) : [...current, province]); markDirty(); }} />)}</div></div></SettingCard></div>; }

function PricingTab({ markDirty }: { markDirty: () => void }) { const [price, setPrice] = useState("10"); const [trial, setTrial] = useState("2"); const [autoSuspend, setAutoSuspend] = useState(false); const [payments, setPayments] = useState(["Mobile Money — Airtel / M-Pesa / Orange"]); return <div className="space-y-4"><SettingCard title="Paramètres d'abonnement" description="Règles appliquées aux écoles partenaires"><div className="grid gap-4 sm:grid-cols-2"><Field label="Prix mensuel par école ($)" value={price} onChange={(value) => { setPrice(value); markDirty(); }} type="number" /><Field label="Durée de l'essai gratuit (mois)" value={trial} onChange={(value) => { setTrial(value); markDirty(); }} type="number" /></div><div className="mt-4 rounded-md bg-[#f1f8fb] px-3 py-2.5 text-[9px] text-[#617b8a]">Les changements de prix s'appliquent uniquement aux nouveaux renouvellements. Les paiements sont actuellement confirmés manuellement.</div></SettingCard><SettingCard title="Modes de paiement acceptés"><div className="grid gap-1 sm:grid-cols-2">{["Mobile Money — Airtel / M-Pesa / Orange", "Virement bancaire", "Espèces via agent"].map((payment) => <CheckOption key={payment} label={payment} checked={payments.includes(payment)} onChange={() => { setPayments((current) => current.includes(payment) ? current.filter((item) => item !== payment) : [...current, payment]); markDirty(); }} />)}</div></SettingCard><SettingCard title="Gestion des retards" description="Le contrôle automatique est désactivé par défaut car la facturation reste manuelle"><ToggleRow title="Suspendre automatiquement une école après retard" description="Les écoles sont actuellement suspendues après vérification manuelle de l'équipe." enabled={autoSuspend} onChange={() => { setAutoSuspend(!autoSuspend); markDirty(); }} />{autoSuspend && <div className="mt-3 max-w-[230px]"><Field label="Nombre de jours de retard" value="10" onChange={markDirty} type="number" /></div>}</SettingCard></div>; }

function NotificationsTab({ markDirty }: { markDirty: () => void }) { const [events, setEvents] = useState(["Nouvelle inscription école", "Document manquant", "Essai se terminant bientôt", "Paiement en retard"]); const [channels, setChannels] = useState(["Email"]); return <div className="space-y-4"><SettingCard title="Événements à notifier" description="Choisissez les événements qui nécessitent l'attention de l'équipe EduGoma"><div className="divide-y divide-[#edf1f4]">{["Nouvelle inscription école", "Document manquant", "Essai se terminant bientôt", "Paiement en retard", "Incident système"].map((event) => <ToggleRow key={event} title={event} description={`Recevoir une alerte lorsqu'un événement « ${event.toLowerCase()} » est détecté.`} enabled={events.includes(event)} onChange={() => { setEvents((current) => current.includes(event) ? current.filter((item) => item !== event) : [...current, event]); markDirty(); }} />)}</div></SettingCard><SettingCard title="Canaux de notification" description="Les alertes sont envoyées aux coordonnées de l'administrateur plateforme"><div className="flex flex-wrap gap-2">{["Email", "SMS", "Email + SMS"].map((channel) => <CheckOption key={channel} label={channel} checked={channels.includes(channel)} onChange={() => { setChannels([channel]); markDirty(); }} />)}</div><div className="mt-4 grid gap-4 sm:grid-cols-2"><Field label="Adresse email de contact" value="admin@edugoma.cd" onChange={markDirty} /><Field label="Numéro SMS de contact" value="+243 810 000 001" onChange={markDirty} /></div></SettingCard></div>; }

function SecurityTab({ markDirty }: { markDirty: () => void }) { return <div className="space-y-4"><SettingCard title="Contrôle d'accès" description="Protection des comptes administrateurs et des sessions"><ToggleRow title="Authentification à deux facteurs obligatoire" description="Tous les administrateurs doivent confirmer leur identité avec une seconde étape." enabled onChange={markDirty} /><ToggleRow title="Notifier les nouvelles connexions" description="Créer une alerte lors d'une connexion depuis un nouvel appareil." enabled onChange={markDirty} /></SettingCard><SettingCard title="Politique de mot de passe"><div className="grid gap-4 sm:grid-cols-2"><Field label="Longueur minimale" value="10 caractères" onChange={markDirty} /><Field label="Expiration" value="90 jours" onChange={markDirty} /></div><div className="mt-3 flex flex-wrap gap-2"><CheckOption label="Majuscules requises" checked onChange={markDirty} /><CheckOption label="Chiffres requis" checked onChange={markDirty} /><CheckOption label="Caractère spécial requis" checked onChange={markDirty} /></div></SettingCard><SettingCard title="Sessions actives" description="Sessions d'administration actuellement ouvertes"><div className="overflow-x-auto"><table className="w-full min-w-[560px] text-left"><thead><tr className="bg-[#f8fafc] text-[8px] font-bold uppercase tracking-[0.06em] text-[#83909c]"><th className="px-3 py-2">Appareil</th><th className="px-3 py-2">Localisation</th><th className="px-3 py-2">Dernière activité</th><th className="px-3 py-2 text-right">Action</th></tr></thead><tbody>{[["Chrome · macOS", "Goma, RDC", "il y a 4m"], ["Safari · iPhone", "Bukavu, RDC", "il y a 2h"], ["Edge · Windows", "Kinshasa, RDC", "il y a 1j"]].map((session) => <tr key={session[0]} className="border-t border-[#edf1f4] text-[9px] text-[#71818e]"><td className="px-3 py-2.5 font-semibold text-[#516a7a]">{session[0]}</td><td className="px-3 py-2.5">{session[1]}</td><td className="px-3 py-2.5">{session[2]}</td><td className="px-3 py-2.5 text-right"><button onClick={markDirty} className="text-[9px] font-bold text-[#c25e67] hover:underline">Déconnecter</button></td></tr>)}</tbody></table></div></SettingCard></div>; }

function TeamTab({ markDirty }: { markDirty: () => void }) { return <SettingCard title="Membres de l'équipe EduGoma" description="Administrateurs internes, indépendants des comptes utilisateurs des écoles"><div className="mb-3 flex justify-end"><button onClick={markDirty} className="flex items-center gap-1.5 rounded-md bg-[#102d48] px-3 py-2 text-[9px] font-bold text-white hover:bg-[#193d5e]"><Plus size={12} /> Inviter un membre</button></div><div className="overflow-x-auto"><table className="w-full min-w-[620px] text-left"><thead><tr className="bg-[#f8fafc] text-[8px] font-bold uppercase tracking-[0.06em] text-[#83909c]"><th className="px-3 py-2">Nom</th><th className="px-3 py-2">Email</th><th className="px-3 py-2">Rôle</th><th className="px-3 py-2">Statut</th><th className="px-3 py-2 text-right">Actions</th></tr></thead><tbody>{[["Dr. Julien Makiese", "superadmin@edugoma.cd", "Super Admin", "Actif"], ["Aline Kabuya", "al.kabuya@edugoma.cd", "Facturation", "Actif"], ["Patrick Okito", "support@edugoma.cd", "Support", "Actif"]].map((member) => <tr key={member[1]} className="border-t border-[#edf1f4] text-[9px] text-[#71818e]"><td className="px-3 py-3 font-bold text-[#516a7a]"><span className="mr-2 inline-flex h-6 w-6 items-center justify-center rounded-full bg-[#e5eef3] text-[8px] font-bold text-[#4a6e84]">{member[0].split(" ").map((part) => part[0]).slice(-2).join("")}</span>{member[0]}</td><td className="px-3 py-3">{member[1]}</td><td className="px-3 py-3"><span className="rounded bg-[#e6f1fc] px-2 py-1 text-[8px] font-bold text-[#4a86b7]">{member[2]}</span></td><td className="px-3 py-3"><span className="rounded bg-[#e5f7ef] px-2 py-1 text-[8px] font-bold text-[#379d78]">{member[3]}</span></td><td className="px-3 py-3 text-right"><button onClick={markDirty} className="text-[9px] font-bold text-[#557f9c] hover:underline">Modifier</button></td></tr>)}</tbody></table></div></SettingCard>; }

function IntegrationsTab({ markDirty }: { markDirty: () => void }) {
  const integrations = [
    { name: "Mobile Money", description: "Airtel Money, M-Pesa et Orange Money", status: "Connecté", tone: "green", icon: Smartphone },
    { name: "Passerelle SMS", description: "Notifications transactionnelles et alertes", status: "Non connecté", tone: "gray", icon: Bell },
    { name: "WhatsApp Business API", description: "Communications opérationnelles ciblées", status: "Non connecté", tone: "gray", icon: MessageIcon },
  ];
  return <div className="grid gap-4 sm:grid-cols-2">{integrations.map((integration) => { const Icon = integration.icon; return <section key={integration.name} className="rounded-md border border-[#e4eaf0] bg-white p-4 shadow-[0_2px_7px_rgba(33,60,84,0.025)]"><div className="flex items-start justify-between"><span className="flex h-9 w-9 items-center justify-center rounded-lg bg-[#eef3f7] text-[#577a90]"><Icon size={17} /></span><span className={`rounded px-2 py-1 text-[8px] font-bold ${integration.tone === "green" ? "bg-[#e5f7ef] text-[#379d78]" : "bg-[#eef2f5] text-[#71808d]"}`}>{integration.status}</span></div><h2 className="mt-3 text-[12px] font-bold text-[#40596b]">{integration.name}</h2><p className="mt-1 text-[9px] leading-relaxed text-[#8a98a2]">{integration.description}</p><button onClick={markDirty} className="mt-4 rounded-md border border-[#dfe7ec] px-3 py-2 text-[9px] font-bold text-[#607887] hover:bg-[#f5f8fa]">Configurer</button></section>; })}</div>;
}
function MessageIcon(props: { size?: number }) { return <Wifi {...props} />; }

export default function Settings() {  const [tab, setTab] = useState<TabId>("general"); const [dirty, setDirty] = useState(false); const [notice, setNotice] = useState(""); const markDirty = () => { setDirty(true); setNotice(""); }; const save = () => { setDirty(false); setNotice("Les modifications ont été enregistrées."); }; const content = tab === "general" ? <GeneralTab markDirty={markDirty} /> : tab === "pricing" ? <PricingTab markDirty={markDirty} /> : tab === "notifications" ? <NotificationsTab markDirty={markDirty} /> : tab === "security" ? <SecurityTab markDirty={markDirty} /> : tab === "team" ? <TeamTab markDirty={markDirty} /> : <IntegrationsTab markDirty={markDirty} />; return (<><div className="mb-5"><div className="mb-2 flex items-center gap-1.5 text-[9px] text-[#81909d]"><span className="rounded bg-[#e8f1f7] px-2 py-1 font-bold uppercase tracking-[0.07em] text-[#436b85]">▦ EDUGOMA SAAS › PLATFORM CONTROL CENTER</span><span>•</span><span>Administration</span></div><h1 className="text-[23px] font-bold tracking-[-0.04em] text-[#172f45]">Paramètres</h1><p className="mt-1 text-[11px] text-[#778894]">Configuration générale de la plateforme EduGoma</p></div>{notice && <div className="mb-3 flex items-center justify-between rounded-md border border-[#cde9dc] bg-[#effaf5] px-3 py-2 text-[10px] font-semibold text-[#2b8e6b]">{notice}<button onClick={() => setNotice("")}><X size={13} /></button></div>}<div className="grid grid-cols-1 items-start gap-4 lg:grid-cols-[235px_minmax(0,1fr)]"><nav className="rounded-md border border-[#e4eaf0] bg-white p-2 shadow-[0_2px_7px_rgba(33,60,84,0.025)]">{tabs.map((item) => <button key={item.id} onClick={() => { setTab(item.id); setNotice(""); }} className={`flex w-full items-center gap-2.5 rounded-md px-3 py-2.5 text-left transition ${tab === item.id ? "bg-[#102d48] text-white" : "text-[#617786] hover:bg-[#f3f7f9]"}`}><span className={`flex h-6 w-6 items-center justify-center rounded-md ${tab === item.id ? "bg-[#214863] text-[#a6d9ca]" : "bg-[#eef3f7] text-[#648196]"}`}><SettingsIcon size={12} /></span><span className="min-w-0 flex-1"><span className="block text-[10px] font-bold">{item.label}</span><span className={`mt-0.5 block truncate text-[8px] ${tab === item.id ? "text-[#c0d1dc]" : "text-[#96a3ac]"}`}>{item.description}</span></span><ChevronRight size={12} /></button>)}</nav><div className="min-w-0">{content}{dirty && <div className="sticky bottom-0 z-20 mt-4 flex items-center justify-between gap-3 rounded-md border border-[#dfe8ec] bg-white/95 px-4 py-3 shadow-[0_-4px_14px_rgba(33,60,84,0.06)] backdrop-blur-sm"><span className="text-[9px] font-semibold text-[#ba7938]">Modifications non enregistrées</span><button onClick={save} className="flex items-center gap-2 rounded-md bg-[#102d48] px-3 py-2 text-[9px] font-bold text-white hover:bg-[#193d5e]"><Save size={12} /> Enregistrer les modifications</button></div>}</div></div></>); }

