"use client";

import { BarChart3, CalendarDays, CheckCircle2, Download, GraduationCap, LineChart, PieChart, Table2, Users, X } from "lucide-react";
import { useState } from "react";


type ReportTab = "Croissance" | "Revenus" | "Adoption" | "Écoles";

function Panel({ children, className = "" }: { children: React.ReactNode; className?: string }) { return <section className={`rounded-md border border-[#e4eaf0] bg-white shadow-[0_2px_7px_rgba(33,60,84,0.025)] ${className}`}>{children}</section>; }
function Metric({ label, value, detail, tone = "blue" }: { label: string; value: string; detail: string; tone?: "blue" | "green" | "orange" | "violet" }) { const styles = { blue: "bg-[#e6f1fc] text-[#4a86b7]", green: "bg-[#e5f7ef] text-[#379d78]", orange: "bg-[#fff0db] text-[#ba7938]", violet: "bg-[#f0edff] text-[#7167bd]" }; return <div className="rounded-md border border-[#e4eaf0] bg-white p-3.5 shadow-[0_2px_7px_rgba(33,60,84,0.025)]"><p className="text-[9px] font-bold uppercase tracking-[0.05em] text-[#85919d]">{label}</p><p className="mt-2 text-[22px] font-extrabold tracking-[-0.05em] text-[#182f45]">{value}</p><span className={`mt-2 inline-block rounded px-1.5 py-1 text-[8px] font-bold ${styles[tone]}`}>{detail}</span></div>; }
function GrowthChart() { return <Panel><div className="flex flex-wrap items-start justify-between gap-3 border-b border-[#edf1f4] px-4 py-3"><div><p className="text-[9px] font-bold uppercase tracking-[0.08em] text-[#8996a1]">Métriques d'adoption &amp; réseau scolaire</p><h2 className="mt-1 text-[13px] font-bold text-[#23394e]">Croissance du Parc Écoles &amp; Demandes de démo</h2></div><div className="flex gap-4 text-[8px] text-[#71818e]"><span><i className="mr-1 inline-block h-2 w-2 rounded-full bg-[#162334]" />Écoles clientes actives</span><span><i className="mr-1 inline-block h-2 w-2 rounded-full bg-[#315d7a]" />Demandes de démo converties</span></div></div><div className="relative h-[270px] p-4"><div className="absolute inset-x-12 inset-y-5 flex flex-col justify-between">{[0, 1, 2, 3, 4].map((line) => <span key={line} className="border-t border-dashed border-[#e6ebef]" />)}</div><div className="absolute left-3 top-4 bottom-7 flex flex-col justify-between text-[8px] text-[#9aa6b1]"><span>200</span><span>150</span><span>100</span><span>50</span><span>0</span></div><svg viewBox="0 0 700 220" preserveAspectRatio="none" className="absolute inset-x-12 inset-y-5 h-[220px] w-[calc(100%-96px)]"><path d="M0 192 C85 180 130 164 208 149 S340 112 410 91 S545 48 700 18" fill="none" stroke="#162334" strokeWidth="3" /><path d="M0 211 C80 201 140 188 208 177 S337 148 410 128 S550 91 700 58" fill="none" stroke="#315d7a" strokeDasharray="7 5" strokeWidth="2.5" /><path d="M0 192 C85 180 130 164 208 149 S340 112 410 91 S545 48 700 18 L700 220 L0 220 Z" fill="url(#reportArea)" opacity=".28" /><defs><linearGradient id="reportArea" x1="0" x2="0" y1="0" y2="1"><stop stopColor="#b8d6e6" /><stop offset="1" stopColor="#eff6fa" /></linearGradient></defs></svg><div className="absolute bottom-1 left-12 right-12 flex justify-between text-[8px] text-[#8995a0]"><span>Mai 2024</span><span>Juin</span><span>Juil</span><span>Août</span><span>Sep</span><span className="font-bold text-[#4b5d6d]">Oct 2024</span></div><div className="absolute right-3 top-4 bottom-7 flex flex-col justify-between text-[8px] text-[#9aa6b1]"><span>130k</span><span>90k</span><span>60k</span><span>30k</span><span>0</span></div></div></Panel>; }
function RevenueView() { const bars = [42, 48, 54, 61, 68, 74]; return <div className="space-y-4"><div className="grid grid-cols-1 gap-3 sm:grid-cols-3"><Metric label="MRR actuel" value="$1,840" detail="+8,4% ce mois" tone="green" /><Metric label="Conversion essai → payant" value="76.2%" detail="+5,1 pts" tone="blue" /><Metric label="Taux de désabonnement" value="1.8%" detail="Dans la cible < 3%" tone="orange" /></div><Panel><div className="border-b border-[#edf1f4] px-4 py-3"><p className="text-[9px] font-bold uppercase tracking-[0.08em] text-[#8996a1]">Revenus mensuels</p><h2 className="mt-1 text-[13px] font-bold text-[#23394e]">Progression du revenu récurrent</h2></div><div className="flex h-[245px] items-end gap-5 px-8 pb-8 pt-6">{bars.map((height, index) => <div key={index} className="flex h-full flex-1 flex-col items-center justify-end gap-2"><div className="w-full max-w-[55px] rounded-t bg-[#6ba9c7]" style={{ height: `${height * 2.5}px` }} /><span className="text-[8px] text-[#8995a0]">{["Mai", "Juin", "Juil", "Août", "Sep", "Oct"][index]}</span></div>)}</div></Panel><Panel><div className="border-b border-[#edf1f4] px-4 py-3"><h2 className="text-[12px] font-bold text-[#23394e]">Répartition du revenu</h2></div><div className="grid gap-3 p-4 sm:grid-cols-3"><div className="rounded bg-[#e5f7ef] p-3"><p className="text-[9px] text-[#5d7d70]">Revenu actif (payant)</p><p className="mt-1 text-[16px] font-extrabold text-[#2e8e6c]">$1,840</p></div><div className="rounded bg-[#e6f1fc] p-3"><p className="text-[9px] text-[#5b7e98]">Revenu en essai (potentiel)</p><p className="mt-1 text-[16px] font-extrabold text-[#4a86b7]">$120</p><p className="text-[8px] text-[#7c94a3]">12 écoles · $0 actuel</p></div><div className="rounded bg-[#ffe5e5] p-3"><p className="text-[9px] text-[#986c70]">Revenu perdu</p><p className="mt-1 text-[16px] font-extrabold text-[#c25e67]">$40</p><p className="text-[8px] text-[#a78387]">4 désabonnements</p></div></div></Panel></div>; }
function AdoptionView() { const rows = [["Institut Mwangaza de Goma", "1,240", "il y a 12m", "Élèves · Notes · Présences"], ["Collège Alfajiri", "2,860", "il y a 25m", "Élèves · Paiements · Notes"], ["Lycée Amanzi EDUG", "3,420", "il y a 1j", "Élèves · Notes"], ["Institut Technique Industriel", "980", "il y a 6h", "Élèves · Présences · Rapports"]]; return <div className="space-y-4"><div className="grid grid-cols-1 gap-3 sm:grid-cols-3"><Metric label="Délai moyen d'onboarding" value="—" detail="Aucune donnée" tone="green" /><Metric label="Demandes de démo converties" value="—" detail="Aucune donnée" tone="blue" /><Metric label="Utilisateurs actifs / école" value="—" detail="Aucune donnée" tone="violet" /></div><Panel><div className="border-b border-[#edf1f4] px-4 py-3"><h2 className="text-[12px] font-bold text-[#23394e]">Adoption par établissement</h2><p className="mt-1 text-[9px] text-[#8a97a4]">Usage observé sur les 30 derniers jours</p></div><div className="overflow-x-auto"><table className="w-full min-w-[650px] text-left"><thead><tr className="bg-[#f8fafc] text-[8px] font-bold uppercase tracking-[0.06em] text-[#83909c]"><th className="px-4 py-2.5">École</th><th className="px-3 py-2.5">Élèves inscrits</th><th className="px-3 py-2.5">Dernière activité</th><th className="px-3 py-2.5">Modules utilisés</th></tr></thead><tbody>{rows.map((row) => <tr key={row[0]} className="border-t border-[#edf1f4] text-[9px] text-[#71818e]"><td className="px-4 py-3 font-semibold text-[#4e6575]">{row[0]}</td><td className="px-3 py-3 font-bold">{row[1]}</td><td className="px-3 py-3">{row[2]}</td><td className="px-3 py-3">{row[3]}</td></tr>)}</tbody></table></div></Panel></div>; }
function SchoolsView() { const provinces = [["Nord-Kivu", 112], ["Sud-Kivu", 38], ["Kinshasa", 22], ["Ituri", 8], ["Autres", 4]]; return <div className="grid grid-cols-1 gap-4 lg:grid-cols-2"><Panel><div className="border-b border-[#edf1f4] px-4 py-3"><h2 className="text-[12px] font-bold text-[#23394e]">Répartition par province</h2><p className="mt-1 text-[9px] text-[#8a97a4]">184 établissements partenaires</p></div><div className="space-y-4 p-4">{provinces.map(([name, value]) => <div key={name}><div className="flex justify-between text-[9px] font-semibold text-[#657b89]"><span>{name}</span><span>{value} écoles</span></div><div className="mt-1.5 h-2 rounded-full bg-[#edf2f4]"><div className="h-full rounded-full bg-[#5c98b7]" style={{ width: `${(Number(value) / 112) * 100}%` }} /></div></div>)}</div></Panel><Panel><div className="border-b border-[#edf1f4] px-4 py-3"><h2 className="text-[12px] font-bold text-[#23394e]">Répartition par statut</h2><p className="mt-1 text-[9px] text-[#8a97a4]">État actuel du parc EduGoma</p></div><div className="grid grid-cols-2 gap-3 p-4"><div className="col-span-2 flex items-center gap-6"><div className="relative flex h-32 w-32 items-center justify-center rounded-full" style={{ background: "conic-gradient(#55aa88 0 74%, #65a4c1 74% 87%, #d7a159 87% 98%, #d26a72 98% 100%)" }}><div className="flex h-20 w-20 items-center justify-center rounded-full bg-white text-center"><span className="text-[18px] font-extrabold text-[#243e54]">184</span></div></div><div className="space-y-2 text-[9px] text-[#687d8c]"><p><i className="mr-2 inline-block h-2 w-2 rounded-full bg-[#55aa88]" />Actives <strong>136</strong></p><p><i className="mr-2 inline-block h-2 w-2 rounded-full bg-[#65a4c1]" />Essai <strong>24</strong></p><p><i className="mr-2 inline-block h-2 w-2 rounded-full bg-[#d7a159]" />En retard <strong>18</strong></p><p><i className="mr-2 inline-block h-2 w-2 rounded-full bg-[#d26a72]" />Suspendues <strong>6</strong></p></div></div></div></Panel></div>; }

export default function Reports() {
  
  const [tab, setTab] = useState<ReportTab>("Croissance");
  const [range, setRange] = useState("Mai - Oct 2024");
  const [notice, setNotice] = useState("");
  const content = tab === "Croissance" ? <div className="space-y-4"><GrowthChart /><div className="grid grid-cols-1 gap-3 sm:grid-cols-3"><Metric label="Nouvelles écoles ce mois" value="12" detail="+20% vs septembre" tone="green" /><Metric label="Taux de croissance mensuel" value="6.9%" detail="Au-dessus de l'objectif" tone="blue" /><Metric label="Objectif annuel" value="92%" detail="184 / 200 écoles" tone="violet" /></div></div> : tab === "Revenus" ? <RevenueView /> : tab === "Adoption" ? <AdoptionView /> : <SchoolsView />;
  return (<><div className="mb-5 flex flex-wrap items-end justify-between gap-4"><div><div className="mb-2 flex items-center gap-1.5 text-[9px] text-[#81909d]"><span className="rounded bg-[#e8f1f7] px-2 py-1 font-bold uppercase tracking-[0.07em] text-[#436b85]">▦ EDUGOMA SAAS › PLATFORM CONTROL CENTER</span><span>•</span><span>Business intelligence</span></div><h1 className="text-[23px] font-bold tracking-[-0.04em] text-[#172f45]">Rapports</h1><p className="mt-1 text-[11px] text-[#778894]">Suivi de la croissance, de l'adoption et des revenus de la plateforme EduGoma</p></div><div className="flex flex-wrap gap-2"><label className="relative flex h-8 items-center"><CalendarDays size={12} className="pointer-events-none absolute left-2.5 text-[#718696]" /><select value={range} onChange={(event) => setRange(event.target.value)} className="h-8 appearance-none rounded-md border border-[#dce5eb] bg-white pl-8 pr-8 text-[10px] font-semibold text-[#536b7d] outline-none"><option>Mai - Oct 2024</option><option>Jan - Oct 2024</option><option>30 derniers jours</option></select><span className="pointer-events-none absolute right-2.5 text-[#8293a0]">⌄</span></label><button onClick={() => setNotice("Le rapport est prêt à être exporté.")} className="flex h-8 items-center gap-2 rounded-md border border-[#dce5eb] bg-white px-3 text-[10px] font-bold text-[#55758a] hover:bg-[#f5f8fa]"><Download size={13} /> Exporter (PDF/CSV)</button></div></div>{notice && <div className="mb-3 flex items-center justify-between rounded-md border border-[#cde9dc] bg-[#effaf5] px-3 py-2 text-[10px] font-semibold text-[#2b8e6b]">{notice}<button onClick={() => setNotice("")}><X size={13} /></button></div>}<div className="mb-4 flex flex-wrap items-center gap-1 border-b border-[#dfe7ed]">{(["Croissance", "Revenus", "Adoption", "Écoles"] as ReportTab[]).map((item) => <button key={item} onClick={() => setTab(item)} className={`flex items-center gap-1.5 rounded-t-md px-3 py-2 text-[10px] font-bold ${tab === item ? "border-b-2 border-[#102d48] bg-white text-[#263e54]" : "text-[#788896] hover:text-[#29465d]"}`}>{item === "Croissance" ? <LineChart size={12} /> : item === "Revenus" ? <BarChart3 size={12} /> : item === "Adoption" ? <Table2 size={12} /> : <PieChart size={12} />}{item}</button>)}</div>{content}</>);
}

